pipeline {
    agent any
    parameters {
        credentials(name: 'LoginSemana4', description: 'Credenciales de usuario y contraseña')
    }
    stages {
        stage('Preparar directorio de trabajo') {
            steps {
                script {
                    // Eliminar cualquier directorio existente para evitar conflictos
                    sh '''
                    if [ -d "threepoints_devops_webserver_Steven" ]; then
                        echo "Eliminando directorio existente..."
                        rm -rf threepoints_devops_webserver_Steven
                    fi
                    '''
                    echo 'Directorio limpio y preparado para el clon.'
                }
            }
        }
        stage('Clonar repositorio y obtener la rama') {
            steps {
                script {
                    // Clonamos el repositorio
                    sh '''
                    git clone https://github.com/stevengazu/threepoints_devops_webserver_Steven.git
                    '''
                    sh '''
                    cd threepoints_devops_webserver_Steven
                    git checkout Pruebas
                    '''

                    // Obtenemos la rama actual directamente desde el repositorio clonado
                    env.BRANCH_NAME = sh(script: '''
                    git rev-parse --abbrev-ref HEAD
                    ''', returnStdout: true).trim()
                    
                    // Mensaje para confirmar la rama detectada
                    echo "La rama actual detectada es '${env.BRANCH_NAME}'"
                }
            }
        }
        stage('Validar rama') {
            steps {
                script {
                    // Validamos si la rama es permitida
                    if (!(env.BRANCH_NAME ==~ /(master|feature-.+|hotfix-.+)/)) {
                        error "El pipeline no está configurado para ejecutarse en la rama '${env.BRANCH_NAME}'."
                    }
                    echo "Ejecutando pipeline para la rama permitida '${env.BRANCH_NAME}'."
                }
            }
        }
        stage('Pruebas de SAST') {
            steps {
                echo 'Ejecución de pruebas de SAST'
            }
        }
        stage('Crear archivo de credenciales') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'LoginSemana4', 
                        usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        writeFile file: 'credentials.ini', text: """
                        [credentials]
                        user=${USERNAME}
                        password=${PASSWORD}
                        """
                        echo 'Archivo credentials.ini creado con éxito.'
                    }
                }
            }
        }
        stage('Build docker image') {
            steps {
                script {
                    echo 'Construyendo la imagen Docker...'
                    sh '''
                    cd threepoints_devops_webserver_Steven
                    docker build -t devops_ws_eje3 .
                    '''
                    echo 'Imagen Docker construida con éxito.'
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'credentials.ini', fingerprint: true
            echo 'Pipeline finalizado exitosamente.'
        }
    }
}